# Generated by Django 5.2.9 on 2025-12-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instagram_user', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Post')),
                ('rede_social', models.CharField(choices=[('reels', 'Instagram Reels'), ('feed', 'Instagram Feed'), ('stories', 'Instagram Stories'), ('tiktok', 'TikTok'), ('youtube', 'YouTube Shorts')], default='reels', max_length=20, verbose_name='Rede Social')),
                ('descricao_legenda', models.TextField(help_text='Texto que será copiado para o post', verbose_name='Legenda/Descrição')),
                ('data_postagem', models.DateTimeField(verbose_name='Data/Hora da Postagem')),
                ('status', models.CharField(choices=[('ideia', '💡 Ideia/Pauta'), ('producao', '🎬 Em Produção'), ('revisao', '👀 Aguardando Revisão'), ('agendado', '🗓️ Agendado'), ('postado', '✅ Postado')], default='ideia', max_length=20)),
                ('link_video_dropbox', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Vídeo (Dropbox)')),
                ('link_capa_dropbox', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da Capa (Dropbox)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['data_postagem'],
            },
        ),
    ]
