# Generated by Django 5.2.9 on 2025-12-30 19:33

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instagram_user', models.CharField(blank=True, max_length=50)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='posts.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Post')),
                ('rede_social', models.CharField(choices=[('reels', 'Instagram Reels'), ('feed', 'Instagram Feed'), ('stories', 'Instagram Stories'), ('tiktok', 'TikTok'), ('youtube', 'YouTube Shorts')], default='reels', max_length=20, verbose_name='Rede Social')),
                ('data_postagem', models.DateTimeField(verbose_name='Data da Postagem')),
                ('descricao_legenda', models.TextField(blank=True, verbose_name='Legenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('planejamento', '📝 Planejamento/Roteiro'), ('captacao', '🎥 Captação'), ('edicao', '🎬 Edição'), ('aprovacao', '✅ Aprovação'), ('postagem', '📱 Postagem')], max_length=20)),
                ('prazo', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='Local (Se captação)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Instruções/Roteiro')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='posts.post')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=posts.models.caminho_arquivo_dropbox)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='posts.tarefa')),
            ],
        ),
    ]
