# Generated by Django 5.2.9 on 2025-12-28 20:04

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_capa_dropbox',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_video_dropbox',
        ),
        migrations.AddField(
            model_name='post',
            name='arquivo_capa',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.caminho_arquivo_dropbox, verbose_name='Capa do Vídeo'),
        ),
        migrations.AddField(
            model_name='post',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.caminho_arquivo_dropbox, verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao_legenda',
            field=models.TextField(blank=True, help_text='Texto que será copiado para o post', verbose_name='Legenda/Descrição'),
        ),
    ]
