# Generated by Django 5.2.9 on 2026-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='instagram',
        ),
        migrations.AddField(
            model_name='cliente',
            name='redes_sociais',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
