# Generated by Django 5.2.9 on 2026-01-02 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cliente_facebook_remove_cliente_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX para Cobrança'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minha_agencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
