# Generated by Django 5.2.9 on 2026-01-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agencia_bairro_agencia_cep_agencia_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='redes_sociais',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
