# Generated by Django 5.2.9 on 2026-01-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agencia_redes_sociais_alter_agencia_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp do Contato'),
        ),
    ]
