# Generated by Django 5.2.9 on 2026-01-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_nome_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Post')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('rede_social', models.CharField(max_length=50, verbose_name='Rede Social')),
                ('legenda', models.TextField(blank=True, null=True)),
                ('briefing_arte', models.TextField(blank=True, null=True, verbose_name='Instruções para Arte')),
                ('imagem_preview', models.ImageField(blank=True, null=True, upload_to='posts/previews/')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('redacao', 'Em Redação'), ('design', 'Em Design'), ('aprovacao', 'Aguardando Aprovação'), ('ajuste', 'Ajuste Solicitado'), ('agendado', 'Agendado'), ('postado', 'Postado')], default='planejamento', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.cliente')),
            ],
        ),
    ]
