# Generated by Django 5.2.9 on 2026-01-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='redes_sociais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.AddField(
            model_name='agencia',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Contato'),
        ),
    ]
