# Generated by Django 5.2.9 on 2026-01-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agencia_endereco_remove_agencia_redes_sociais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='agencia',
            name='config_redes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cliente',
            name='eh_perfil_agencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp_contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
