# Generated by Django 5.2.9 on 2026-01-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_agencia_config_redes_agencia_redes_sociais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropbox_config', to='core.agencia')),
            ],
        ),
    ]
