# Generated by Django 5.2.9 on 2026-01-07 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_post_cliente_remove_post_data_criacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='eh_perfil_agencia',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='ativo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/logos/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='briefing_arte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='legenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='rede_social',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linktree', 'Linktree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('aprovacao', 'Aguardando Aprovação'), ('ajuste', 'Ajuste Solicitado'), ('agendado', 'Agendado'), ('postado', 'Postado')], default='planejamento', max_length=20),
        ),
    ]
