# Generated by Django 5.2.9 on 2026-01-07 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_agencia_chave_pix_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cronograma',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_cliente',
        ),
        migrations.RemoveField(
            model_name='dropboxconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicopost',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='agencia',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='formato',
            field=models.CharField(choices=[('feed_estatico', 'Feed - Foto Única'), ('feed_carrossel', 'Feed - Carrossel'), ('reels', 'Reels (Vídeo Vertical)'), ('stories', 'Stories (Foto/Vídeo)'), ('video_longo', 'Vídeo Longo (YouTube)')], default='feed_estatico', max_length=50),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='email',
            field=models.EmailField(default='contato@agencyos.com.br', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nome_fantasia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='contato@agencyos.com.br', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='rede_social',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('redacao', 'Em Redação'), ('design', 'Em Design'), ('aprovacao', 'Aguardando Aprovação'), ('ajuste', 'Ajuste Solicitado'), ('agendado', 'Agendado'), ('postado', 'Postado')], default='planejamento', max_length=20),
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='arquivo_pdf',
        ),
    ]
