# Generated by Django 5.2.9 on 2026-01-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cronograma_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_preview',
            field=models.FileField(blank=True, null=True, upload_to='posts/previews/'),
        ),
    ]
