# Generated by Django 5.2.9 on 2026-01-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_post_rede_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ')], default='PJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ')], default='PJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='dropboxconfig',
            name='agencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.agencia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='formato',
            field=models.CharField(choices=[('feed_estatico', 'Feed - Foto Única'), ('feed_carrossel', 'Feed - Carrossel'), ('reels', 'Reels (Vídeo Vertical)'), ('stories', 'Stories (Foto/Vídeo)'), ('video_longo', 'Vídeo Longo (YouTube)')], max_length=50),
        ),
        migrations.DeleteModel(
            name='HistoricoPost',
        ),
    ]
