# Generated by Django 5.2.9 on 2026-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cronograma_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'PESSOA FISICA'), ('PJ', 'PESSOA JURIDICA')], default='PJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'PESSOA FISICA'), ('PJ', 'PESSOA JURIDICA')], default='PJ', max_length=2),
        ),
    ]
