# Generated by Django 5.2.9 on 2026-01-07 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_agencia_tipo_pessoa_alter_cliente_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxconfig',
            name='agencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropbox_config', to='core.agencia'),
        ),
    ]
