# Generated by Django 5.2.9 on 2026-01-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_dropboxconfig_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
