# Generated by Django 5.2.9 on 2026-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cronograma_data_exclusao_cronograma_excluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='titulo',
            field=models.CharField(default='Geral', max_length=100),
        ),
    ]
