# Generated by Django 5.2.9 on 2026-01-07 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cronograma_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='posts/previews/')),
                ('dropbox_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.post')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
