# Generated by Django 5.2.9 on 2026-01-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_postarquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'PESSOA FISICA'), ('PJ', 'PESSOA JURÍDICA')], default='PJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'PESSOA FISICA'), ('PJ', 'PESSOA JURÍDICA')], default='PJ', max_length=2),
        ),
    ]
