# Generated by Django 5.2.9 on 2026-01-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_agencia_tipo_pessoa_alter_cliente_tipo_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
