# Generated by Django 5.2.9 on 2026-01-09 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_agencia_dono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_acesso',
        ),
        migrations.AddField(
            model_name='agencia',
            name='socios',
            field=models.ManyToManyField(blank=True, related_name='agencias_socio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='clientes_acesso', to=settings.AUTH_USER_MODEL),
        ),
    ]
