# Generated by Django 5.2.9 on 2026-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_agencia_dono_remove_cliente_usuario_acesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='pdf_dropbox_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='pdf_dropbox_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
