# Generated by Django 5.2.9 on 2026-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cronograma_pdf_dropbox_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='logo_dropbox_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logo_dropbox_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
