# Generated by Django 5.2.9 on 2026-01-09 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agencia_logo_dropbox_link_cliente_logo_dropbox_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token_convite',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
