# Generated by Django 5.2.9 on 2026-01-09 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_cliente_token_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='token_convite',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
