# Generated by Django 5.2.9 on 2026-03-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_cliente_token_convite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('titulo', models.CharField(default='Feed 01', max_length=100)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='core.cronograma')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.feed'),
        ),
    ]
