# Generated by Django 5.2.9 on 2026-03-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_feed_post_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rede_social',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='rede_social',
            field=models.CharField(choices=[('linktree', 'Linktree'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='instagram', max_length=20),
        ),
    ]
