# Generated by Django 5.2.9 on 2026-03-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_post_rede_social_cronograma_rede_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='cor_personalizada',
            field=models.CharField(default='#6c5ce7', help_text='Cor Hex', max_length=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cor_personalizada',
            field=models.CharField(default='#6c5ce7', help_text='Cor em formato Hex (ex: #6c5ce7)', max_length=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil_cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencia_vinculada', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
