# Generated by Django 5.2.9 on 2026-03-23 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_agencia_cor_personalizada_cliente_cor_personalizada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='perfil_cliente',
        ),
        migrations.AddField(
            model_name='agencia',
            name='perfil_cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencia_vinculada', to='core.cliente'),
        ),
    ]
