# Generated by Django 5.2.9 on 2026-03-24 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_cargo_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome de quem vai receber o convite', max_length=100)),
                ('email', models.EmailField(help_text='E-mail principal para envio', max_length=254)),
                ('tipo', models.CharField(choices=[('EQUIPE', 'Membro da Equipe'), ('CLIENTE', 'Cliente da Agência')], default='EQUIPE', max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aceito', models.BooleanField(default=False)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.agencia')),
                ('cliente_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='core.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
