# Generated by Django 5.2.9 on 2026-03-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_convite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Opcional. Ex: Responsável pelas artes.', null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='core.agencia')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('agencia', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='funcoes',
            field=models.ManyToManyField(blank=True, related_name='colaboradores', to='core.funcao'),
        ),
        migrations.AddField(
            model_name='convite',
            name='funcoes',
            field=models.ManyToManyField(blank=True, help_text='Quais funções essa pessoa terá na agência?', to='core.funcao'),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
